import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
import {catalog,convert,defaultState} from '../src/backend.mjs';
import {writeExportBundle} from '../src/export-bundle.mjs';
const data=await catalog();assert(data.clips.includes(defaultState.clip));
const state={...defaultState,weapon:'blaster_high02_a03'};
const preview=await convert(state,'preview',console.log);
const bytes=await fs.readFile(preview.file);assert.equal(bytes.toString('ascii',0,4),'glTF');
const jsonLength=bytes.readUInt32LE(12);const gltf=JSON.parse(bytes.toString('utf8',20,20+jsonLength));
assert(gltf.skins?.length>0);assert(gltf.animations?.length>0);assert.equal(preview.parts.length,15);
assert.equal(gltf.materials.length,10);assert.equal(gltf.images.length,30);assert(gltf.materials.every(m=>!m.pbrMetallicRoughness.metallicRoughnessTexture&&!m.extensions?.KHR_materials_specular?.specularColorTexture));
assert(gltf.materials.every(m=>m.pbrMetallicRoughness.baseColorTexture&&m.normalTexture&&m.alphaMode==='MASK'));
assert.equal(gltf.materials.find(m=>m.name.startsWith('hair ')).alphaCutoff,.75);
assert(gltf.images.every(i=>i.mimeType==='image/png'&&Number.isInteger(i.bufferView)));
const exportState={...state,time:.3,hidden:[preview.parts[0].name]};
const posed=await convert(exportState,'fbx',console.log);
assert((await fs.stat(posed.file)).size>10000);
const exportedFile=path.resolve('output/export-check/Atton-textured.fbx');
const manifest=await writeExportBundle(posed,exportState,exportedFile);
for(const m of manifest.materials)for(const file of Object.values(m.textures))assert((await fs.stat(path.join(path.dirname(exportedFile),file))).size>100);
const completeState={...state,time:preview.duration*.98};
const complete=await convert(completeState,'fbx',console.log);
const completeFile=path.resolve('output/examples/Atton-equipped.fbx');
await writeExportBundle(complete,completeState,completeFile);
await fs.writeFile('reports/app-pipeline-smoke.json',JSON.stringify({ok:true,clips:data.clips.length,gear:data.gear,preview,posed,complete,exportedFile,completeFile,skins:gltf.skins.length,animations:gltf.animations.length,embeddedImages:gltf.images.length},null,2));
console.log('PASS: native decode, equipped skinned GLB, embedded materials, textured FBX bundle');
