import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const build=JSON.parse(await fs.readFile('dist/latest.json','utf8'));
const local=JSON.parse(await fs.readFile('development.local.json','utf8'));
const folder=path.resolve('output/recovery-smoke-'+Date.now()),resources=path.join(folder,'empty-resources'),data=path.join(folder,'data');
await fs.mkdir(resources,{recursive:true});
const app=path.join(build.app,'resources/app'),runtime=path.join(build.app,'resources/runtime');
Object.assign(process.env,{SWTOR_PACKAGED:'1',SWTOR_RESOURCES:resources,SWTOR_DATA:data,SWTOR_GAME:local.game,SWTOR_PYTHON:path.join(runtime,'python/python.exe'),PATH:path.join(process.env.SystemRoot,'System32')});
const {recoverSources,default:sourceFS}=await import(pathToFileURL(path.join(app,'src/resource-files.mjs')));
const {readNativeJba}=await import(pathToFileURL(path.join(app,'tools/native-jba.mjs')));
const {readNativeNetwork}=await import(pathToFileURL(path.join(app,'tools/native-rig.mjs')));
const names=['art/dynamic/spec/bmnnew_skeleton.gr2','anim/humanoid/bmnnew/anim_library.mph','anim/humanoid/bmnnew/cb_pistol_normal_to_combat.jba'];
await recoverSources(resources,names);
const files=await Promise.all(names.map(async name=>({name,bytes:(await sourceFS.stat(path.join(resources,name))).size})));
const animation=readNativeJba(await sourceFS.readFile(path.join(resources,names[2])));
const network=readNativeNetwork(await sourceFS.readFile(path.join(resources,names[1])));
if(!files.every(f=>f.bytes>100)||!animation.tracks||!network.clips.length)throw Error('Recovered data failed native decoding');
if((await fs.readdir(resources)).length)throw Error('Recovery modified the extraction');
await fs.writeFile('reports/standalone-recovery.json',JSON.stringify({ok:true,files,animationTracks:animation.tracks,mappedClips:network.clips.length,sourceUntouched:true},null,2));
console.log('ARCHIVE RECOVERY PASS',files.length,'files;',animation.tracks,'tracks;',network.clips.length,'network records');
